name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

  - name: Run PlatformIO
  run: |
    set -xe
    rm -rf /tmp/WLEDtemp/*
    mkdir -p /tmp/WLEDtemp
    wget https://github.com/atuline/WLED/archive/refs/heads/dev.zip -O /tmp/WLEDtemp/mm.zip
    unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
    WLEDFOLDERNAME=$(find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d)
    cd "$WLEDFOLDERNAME"
    npm install
    cat <<EOF >>platformio.ini
[env:custom_build]
extends = env:soundReactive_esp32dev
build_flags = ${env:soundReactive_esp32dev.build_flags} -D SR_DEBUG -D WLED_AP_SSID_UNIQUE -D WLED_DEBUG -D WLED_DEBUG_HOST="192.168.15.99" -D WLED_DISABLE_HUESYNC -D WLED_DISABLE_2D -D LEDPIN=5 -D BTNPIN=4 -D RLYPIN=0 -D AUDIOPIN=0 -D DMENABLED=0 -D I2S_CKPIN=8 -D WLED_MAX_BUTTONS=4 -D WLED_MAX_USERMODS=6 -D WLED_MAX_BUSSES=3 -D DEFAULT_LED_COUNT=30 -D ABL_MILLIAMPS_DEFAULT=0 -D DEFAULT_LED_TYPE=WS2811 -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB -D WLED_MAX_LEDMAPS=156 -D MAX_LEDS=8192 -D MAX_LEDS_PER_BUS=2048 -D MAX_LED_MEMORY=32000 -D WLED_PWM_FREQ=19531 -D CLIENT_SSID="VIVOFIBRA-5233" -D CLIENT_PASS="JPEJsNQTBn" -D WLED_AP_SSID="WLED-AP" -D WLED_AP_PASS="wled1234" -D USERMOD_DHT -D USERMOD_DHT_CELSIUS
lib_deps = ${env:soundReactive_esp32dev.lib_deps}
  https://github.com/alwynallan/DHT_nonblocking
build_unflags= -D WLED_RELEASE_NAME
EOF
    pio run -e custom_build || pio run -e custom_build

    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
